export const cidadesDF = [  
      'Água Quente',
      'Arapoanga',
      'Águas Claras',
      'Arniqueira',
      'Brazlândia',
      'Candangolândia',
      'Ceilândia',
      'Cruzeiro',
      'Fercal',
      'Gama',
      'Guará',
      'Itapoã',
      'Jardim Botânico',
      'Lago Norte',
      'Lago Sul',
      'Núcleo Bandeirante',
      'Paranoá',
      'Park Way',
      'Planaltina',
      'Plano Piloto',
      'Recanto das Emas',
      'Riacho Fundo',
      'Riacho Fundo II',
      'Samambaia',
      'Santa Maria',
      'São Sebastião',
      'SCIA/Estrutural',
      'SIA',
      'Sobradinho',
      'Sobradinho II',
      'Sol Nascente e Pôr do Sol',
      'Sudoeste/Octogonal',
      'Taguatinga',
      'Varjão',
      'Vicente Pires'
    ]
  
  export default cidadesDF;